# Generated by Django 4.2.4 on 2024-04-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_practice_latitiude_alter_practice_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='latitiude',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='practice',
            name='longitude',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
